# This is an example .goreleaser.yml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com
before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod tidy
builds:
  - env:
      - CGO_ENABLED=0
    main: ./cmd/main.go
    dir: .
    binary: gophkeeper
    goos:
      - linux
      - darwin
      - windows
    flags:
      - -trimpath
    ldflags:
      - -s -w -X github.com/gopherlearning/gophkeeper/internal/conf.buildCommit={{.Commit}} -X github.com/gopherlearning/gophkeeper/internal/conf.buildVersion={{.Version}} -X github.com/gopherlearning/gophkeeper/internal/conf.buildDate={{.CommitDate}}
      - ./usemsan=-msan
archives:
  - files:
      - LICENSE
    format_overrides:
      - goos: windows
        format: zip
    replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
gomod:
  gobinary: go1.19