@startuml usecase
left to right direction
actor Пользователь as u
usecase UC1 #palegreen;line:green as "получает информацию 
о версии и дате сборки бинарного 
файла клиента" 
usecase UC2 #palegreen;line:green as "генерирует мнемоническую
фразу"
usecase UC17  #palegreen;line:green as "вводит мнемоническую
фразу"
usecase UC11 as "проходит 
процедуру аутентификации"
usecase UC3 #palegreen;line:green as "добавляет в клиент 
пары логин/пароль"
usecase UC4  #palegreen;line:green as "добавляет в клиент 
произвольные текстовые 
данные"
usecase UC5  as "добавляет в клиент 
произвольные бинарные 
данные"
usecase UC6 #palegreen;line:green as "добавляет в клиент 
данные банковских 
карт"
usecase UC7  as "добавляет в 
клиент данные OTP 
(one time password)"
usecase UC8  as "добавляет к 
данным лейблы"
usecase UC9  as "добавляет к 
данным теги"
usecase UC10 as "синхронизирует 
данные с сервером"
usecase UC12 #palegreen;line:green as "запрашивает 
данные"
usecase UC13 as "копирует 
пароль"
usecase UC14 as "извлекает 
данные в файл"
usecase UC15 as "отображает 
список сессий"
usecase UC16 as "удаляет 
авторизованную 
сессию"
u -right-> UC1
u -down-> UC3
u -down-> UC4
u -down-> UC5
u -down-> UC6
u -down-> UC7
u -down-> UC8
u -down-> UC9
u -right-> UC10
u -up-> (UC2)
u -up-> (UC17)
(UC17) .up-> (UC11) : include
(UC2) .up-> (UC11) : include
u -up-> UC12
(UC12) .up-> (UC13) : extends
u -up-> UC14
u -left-> UC16
u -left-> UC15
@enduml
